# Generated by Django 5.2 on 2025-10-07 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitemmodel",
            options={"verbose_name": "Cart Item"},
        ),
        migrations.AlterModelOptions(
            name="cartmodel",
            options={"verbose_name": "cart"},
        ),
    ]
