# Generated by Django 5.2 on 2025-10-07 07:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_alter_cartitemmodel_options_alter_cartmodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartmodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
