# Generated by Django 5.2 on 2025-10-08 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_alter_itemmodel_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemImagesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="item_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="item.itemmodel",
                    ),
                ),
            ],
        ),
    ]
