# Generated by Django 5.2 on 2025-10-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0003_itemimagesmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemimagesmodel",
            name="image",
        ),
        migrations.AddField(
            model_name="itemimagesmodel",
            name="image_url",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
