# Generated by Django 5.2 on 2025-10-08 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0004_remove_itemimagesmodel_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemattributesmodel",
            options={"verbose_name": "Item attribute"},
        ),
        migrations.AlterModelOptions(
            name="itemimagesmodel",
            options={"verbose_name": "Item image"},
        ),
    ]
